# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "dora-deploy-demo-elite-state-bucket"
    dynamodb_table = "dora-deploy-demo-elite-lock"
    encrypt        = true
    key            = "bootstrap/terraform.tfstate"
    region         = "us-east-1"
  }
}
