name: Terragrunt Lambda Deployment Plan

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - envs/**/terragrunt.hcl
      - envs/**/vars.yaml
      - .github/**
jobs:
  plan:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
      issues: write
    name: plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_PLAN_IAM_ROLE }}
          role-session-name: github-actions
          aws-region: ${{ vars.AWS_REGION }}

      - uses: alexellis/arkade-get@master
        with:
          vault: latest
          jq: latest
          terragrunt: latest

      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_wrapper: false

      - name: Create planfile
        run: terragrunt run-all plan -no-color -out=./.planfile;ls -l;
        working-directory: envs/dev

      - name: Convert planfile to JSON planfile
        run: ls -l;terragrunt show -json ./envs/dev/.planfile >> ./my-planfile.json

      - name: Create PR comment
        uses: liatrio/terraform-change-pr-commenter@v1.4.0
        with:
          json-file: my-planfile.json

      # - name: Terragrunt plan
      #   run: |
      #     terragrunt run-all plan
      #   working-directory: envs/dev
