name: Terragrunt Lambda Deployment Plan

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - envs/**/terragrunt.hcl
      - envs/**/vars.yaml
      - .github/**
jobs:
  plan:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
      issues: write
    name: plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_PLAN_IAM_ROLE }}
          role-session-name: github-actions
          aws-region: ${{ vars.AWS_REGION }}

      - uses: alexellis/arkade-get@master
        with:
          vault: latest
          jq: latest
          tofu: latest
          terragrunt: latest

      - name: Terragrunt Plan
        id: terragrunt_plan
        run: |
          pwd
          terragrunt run-all init --terragrunt-non-interactive
          terragrunt run-all plan --terragrunt-non-interactive -out plan.out
          terragrunt show --terragrunt-non-interactive -no-color -json plan.out > plan.json
        continue-on-error: true # Continue on error to ensure the plan is added as a comment on the PR.
        working-directory: envs/dev

      - uses: jburns24/terraform-change-pr-commenter@main
        with:
          json-file: envs/dev/plan.json
          expand-comment: "true"
          hide-previous-comments: "true"
          include-plan-job-summary: "true"
          show-changed-resources: "false"
